<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>sentinel_brain</name>
  <version>0.0.0</version>
  <description>ROS2 Python package per a un sistema de control de missió de robot sentinel.</description>
  <maintainer email="bgenem@esalto.es">bgenem</maintainer>
  <license>MIT</license>

  <depend>rclpy</depend>
  <depend>sentinel_interfaces</depend>

  <test_depend>ament_copyright</test_depend>
  <test_depend>ament_flake8</test_depend>
  <test_depend>ament_pep257</test_depend>
  <test_depend>python3-pytest</test_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
